title: 环境学院本科人才培养方案
icon: environment
author: Mr.Hope
time: 2023-09-22T16:59:13.510Z
shareable: true
content:
  - tag: doc
    name: 环境学院本科人才培养方案 (2020)
    url: $file/course-plan/environment/2020.docx

  - tag: title
    text: 历史版本

  - tag: doc
    name: 环境学院本科人才培养方案 (2019)
    url: $file/course-plan/environment/2019.pdf

  - tag: doc
    name: 环境学院本科课程计划 (2015)
    url: $file/course-plan/environment/2015.pdf
